### ISSUE TITLE
Emulate reduced transparency in Polypane 16

### ISSUE THREAD

**Issue by pankajparashar** [pankajparashar/canidev.tools#105]
I'm not sure, if I am using this correctly, but reduced-transparency emulation doesn't appear to be working in Polypane 16. Same [Pen on Chrome](https://www.canidev.tools/emulate-reduced-transparency/chrome) works fine.

![Export-1699138936786](https://github.com/pankajparashar/canidev.tools/assets/38640616/07d4a9b4-bb26-4321-b6f8-420f41ae9a45)

/cc @Kilian

**Comment by Kilian** [comment]
Polypane doesn't (yet) reach into subframes (like iframes) and the way chromium works is that you need to set emulation on each frame separately. 

Codepen demos always show in an iframe so that's why it looks like it doesn't do anything, but it works for people applying reduced transparency to their own sites.

**Comment by pankajparashar** [comment]
Thanks! very insightful.
